name: update
on:
  pull_request:
  schedule:
    - cron: 1/20 * * * *
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true

      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - name: Setup GPG keys
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          git-committer-email: nathanael.esayeas@protonmail.com
          git-committer-name: Nathanael Esayeas
          git-push-gpgsign: false # Github does not currently support GPG signed pushes, only signed commits.
          git-tag-gpgsign: true
          git-commit-gpgsign: true
          git-user-signingkey: true
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Setup git remote
        run: git remote add actions git@github.com:${{ github.repository }}.git

      - name: Update live data
        uses: ghostwriter/curl@main
        with:
          args: "-L --insecure 'https://api.covid19api.com/country/ethiopia?cache=${{ github.run_id }}' | jq '.' > live.json"

      - name: Check updated live.json
        run: |
          cat live.json;
          if [ ! -s live.json ]; then
            git restore live.json
          fi

      - name: Commit live.json updates
        run: |
          if [[ `git status --porcelain` ]]; then
            git add live.json
            git commit -S --signoff -m "Update live.json"
          fi

      - name: Push updates
        run: |
          if [[ "$(git push -u actions main --porcelain)" == *"Done"* ]]; then
            echo "Git push was successful!"
          fi

      - name: Generate README.md
        run: php generate.php

      - name: Check updated README.md
        run: |
          cat README.md;
          if [ ! -s README.md ]; then
            git restore README.md
          fi

      - name: Commit README.md updates
        run: |
          if [[ `git status --porcelain` ]]; then
            git add README.md
            git commit -S --signoff -m "Update README.md"
          fi

      - name: Push updates
        run: |
          if [[ "$(git push -u actions main --porcelain)" == *"Done"* ]]; then
            echo "Git push was successful!"
          fi
