name: update
on:
  schedule:
    - cron: 1/20 * * * *
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          persist-credentials: true

      - name: Setup GPG keys
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_commit_gpgsign: true
          git_committer_email: nathane@users.noreply.github.com
          git_committer_name: nathane
          git_push_gpgsign: false # Github does not currently support GPG signed pushes, only signed commits.
          git_tag_gpgsign: true
          git_user_signingkey: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: Setup git remote
        run: git remote add actions git@github.com:${{ github.repository }}.git

      - name: Update patients data
        timeout-minutes: 2
        uses: nathane/curl@master
        with:
          args: "-L --insecure 'https://api.pmo.gov.et/v1/patients/?format=json&limit=10000000&cache_bust=${{ github.run_id }}' | jq '.' > patients.json"

      - name: Check updated patients.json
        run: |
          if [ ! -s patients.json ]; then
            git restore patients.json
          fi

      - name: Commit patients.json updates
        run: |
          if [[ `git status --porcelain` ]]; then
            git add patients.json
            git commit -S -m "Update patients.json"
          fi

      - name: Update cases data
        uses: nathane/curl@master
        with:
          args: "-L --insecure 'https://api.pmo.gov.et/v1/cases/?format=json&cache_bust=${{ github.run_id }}' | jq '.' > cases.json"

      - name: Check updated cases.json
        run: |
          if [ ! -s cases.json ]; then
            git restore cases.json
          fi

      - name: Commit cases.json updates
        run: |
          if [[ `git status --porcelain` ]]; then
            git add cases.json
            git commit -S -m "Update cases.json"
          fi

      - name: Update stats data
        uses: nathane/curl@master
        with:
          args: "-L --insecure -H 'Cache-Control: no-cache' -H 'Subscription-Key: ${{ secrets.SUBSCRIPTION_KEY }}' 'https://api.smartable.ai/coronavirus/stats/ET?cache_bust=${{ github.run_id }}' | jq '.' > stats.json"

      - name: Check updated stats.json
        run: |
          if [ ! -s stats.json ]; then
            git restore stats.json
          fi

      - name: Commit stats.json updates
        run: |
          if [[ `git status --porcelain` ]]; then
            git add stats.json
            git commit -S -m "Update stats.json"
          fi

      - name: Update timeline data
        uses: nathane/curl@master
        with:
          args: "-L --insecure 'https://api.thevirustracker.com/free-api?countryTimeline=ET&cache_bust=${{ github.run_id }}' | jq '.' > timeline.json"

      - name: Check updated timeline.json
        run: |
          if [ ! -s timeline.json ]; then
            git restore timeline.json
          fi

      - name: Commit timeline.json updates
        run: |
          if [[ `git status --porcelain` ]]; then
            git add timeline.json
            git commit -S -m "Update timeline.json"
          fi

      - name: Push updates
        run: |
          if [[ "$(git push -u actions main --porcelain)" == *"Done"* ]]; then
            echo "Git push was successful!"
          fi
